package com.rfz.appflotal.core.util

object NavScreens {
    const val LOADING = "loadingScreen"
    const val LOGIN = "loginScreen"
    const val HOME = "homescreen"
    const val MARCAS = "marcas_screen"
    const val NUEVA_MARCA = "nuevaMarca"
    const val RENOVADOS = "diseno_renovados_screen"
    const val ORIGINAL = "diseno_original_screen"
    const val MEDIDAS_LLANTAS = "medidasLlantasScreen"
    const val PRODUCTOS = "productoScreen"
    const val NUEVO_PRODUCTO = "producto_screen"
    const val REGISTRO_LLANTAS = "registroLlantasScreen"
    const val REGISTRO_VEHICULOS = "registroVehiculoScreen"
    const val MONTAJE_DESMONTAJE = "montajeDesmontajeScreen"
    const val INICIO = "inicioScreen"
    const val RECUPERAR_CONTRASENIA = "recuperarcontrasenia"
    const val REGISTRAR_USUARIO = "registrarusuario"
    const val INFORMACION_USUARIO = "informacionusuario"
    const val PERMISOS = "permisos"
    const val MARCA_RENOVADA = "marca_renovada"
    const val TERMINOS = "terminos"
    const val INSPECCION = "inspeccion"
    const val MONTAJE = "montaje"
    const val DESMONTAJE = "desmontaje"
    const val DESECHO = "desecho"

    const val REPARARRENOVAR = "reparar-renovar"
}